# @author Mateusz Machalica

MODEL ?= $(shell ls *.pml | head -1)

all: pan

pan.c: $(MODEL) ../lib/state.pml ../lib/ltls.pml
	spin -a $(MODEL)

pan: pan.c
	gcc -O2 -o pan pan.c

clean:
	rm -f _spin_nvr.tmp pan pan.* $(MODEL).trail

