# @author Mateusz Machalica

MODEL=$(shell ls *.pml | head -1)

all: pan

log: $(MODEL) $(MODEL).trail
	spin -t -p $(MODEL)

pan.c: $(MODEL)
	spin -a $(MODEL)

pan: pan.c
	gcc -O2 -o pan pan.c

clean:
	rm -f _spin_nvr.tmp pan pan.* $(MODEL).trail

