#!/bin/bash
# @author Mateusz Machalica

set -e

model=`find . -name "*.pml" | head -1`
spin_opts="-E-I../lib/"
pan_opts="-n -a"
operation=0

while getopts ":m:l:e:nrfSMLtc" opt; do
  case $opt in
    # Overrides default model
    m) model="$OPTARG" ;;
    # Model generation options
    l) spin_opts="$spin_opts -DLTL=$OPTARG" ;;
    e) spin_opts="$spin_opts -DEPILOG=$OPTARG" ;;
    n) spin_opts="$spin_opts -DPROCESSES_NEVER_BLOCK" ;;
    r) spin_opts="$spin_opts -DRESTARTING_PROCESSES" ;;
    # Verifier runtime options
    f) pan_opts="$pan_opts -f" ;;
    S) pan_opts="$pan_opts -m10000000 -w26" ;;
    M) pan_opts="$pan_opts -m50000000 -w27" ;;
    L) pan_opts="$pan_opts -m200000000 -w27" ;;
    # Miscellaneous
    t) operation=1 ;;
    c) operation=2 ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1 ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1 ;;
  esac
done

set -x

if [[ $operation -eq 0 ]]; then
  rm -f *.trail
  spin -a $spin_opts $model
  gcc -O3 -o pan pan.c
  ./pan $pan_opts
elif [[ $operation -eq 1 ]]; then
  spin -t -p $spin_opts $model
elif [[ $operation -eq 2 ]]; then
  rm -f _spin_nvr.tmp pan pan.* *.trail
fi

