#!/bin/bash
# @author Mateusz Machalica

set -e

model=`find . -name "*.pml" | head -1`
spin_opts="-a"
pan_opts="-m10000000 -w26 -n -a"

while getopts ":m:l:e:bfc" opt; do
  case $opt in
    # Overrides default model
    m) model="$OPTARG" ;;
    # Model generation options
    l) spin_opts="$spin_opts -DLTL=$OPTARG" ;;
    e) spin_opts="$spin_opts -DEPILOG=$OPTARG" ;;
    b) spin_opts="$spin_opts -DMAY_BLOCK_LS" ;;
    # Verifier runtime options
    f) pan_opts="$pan_opts -f" ;;
    # Miscellaneous
    c)
      set -x
      rm -f _spin_nvr.tmp pan pan.* *.trail
      exit 0;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1 ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1 ;;
  esac
done

set -x
rm -f *.trail

spin $spin_opts $model
gcc -O3 -o pan pan.c
./pan $pan_opts

